version: "3.9"
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    ports:
      - 5434:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis

  puppeteer:
    build:
      context: ./puppeteer
      dockerfile: Dockerfile.puppeteer
    init: true
    cap_add:
      - SYS_ADMIN
    container_name: puppeteer-chrome
    tty: true
    stdin_open: true
    volumes:
      - ./puppeteer:/app
    working_dir: /app
    environment:
      DISPLAY: ":0.0"

volumes:
  db-data:
  puppeteer: